### ISSUE TITLE
Suggestions on UI and UX

### ISSUE THREAD

**Issue by acem702** [ujen5173/Hashnode#1]
Hey mate you really have a nice project going on here so I was thinking of give some suggestions

-  when users are not login/signup I think it's best you use a banner "join now" instead of showing the github/Google signup buttons 
- there should also be an email and password login 
- finally when someone is logged in I see not reason why that signin as show be there again
- the comments section is not functioning properly and even comment automatically has 2like and comments when there is non
- any Hope's for admin panel incase people like me that might be interested in host and making a community out of the script 
- the share functionality really important 
- the sidebar button is completely useless for now adds something soon

Lovely project I will keep my eye on it and if there is any means I can contact you please drop your info I want you to explain something to me
Thank you

**Comment by Jeevan-Kiran-Lenka** [comment]
Same here

**Comment by ujen5173** [comment]
Hey there,

Thank you for your feedback. I really appreciate your suggestions and here's what I'm planning to do:

1. Once the project reaches v1, I'm gonna get rid of the "Sign in with Google/GitHub" buttons.
2. I'll be adding the option to log in with email and password in the future.
3. Thanks for letting me know about the comment section problem. I have fixed it :)

I'm super excited to let you know that there are lots of cool features coming up, so stay tuned for updates.

I really value your interest in the project. If you have any more questions or need clarification, feel free to email me at ujenbasi1122@gmail.com or discord at _ujen5173_ or [LinkedIn](https://www.linkedin.com/in/ujen-basi-167a4522a/)

If you want to contribute to this project, feel free to contribute.

Thanks again for your feedback.
