### ISSUE TITLE
May I ask when some functions of "Manage your blogs" will be deployed? 

### ISSUE THREAD

**Issue by 0xworkio** [ujen5173/Hashnode#4]
May I ask when some functions of "Manage your blogs" will be deployed? Such as 'pages'、Analytics、Widgets、domain, etc.

**Comment by ujen5173** [comment]
I'll include those once I'm done with my college tasks. If you'd like to incorporate those features, please feel free to do so! 😊

**Comment by 0xworkio** [comment]
Oh, that's great
